// <auto-generated />
using System;
using Inventario_Productos_Tecnologicos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario_Productos_Tecnologicos.Migrations
{
    [DbContext(typeof(TecnoCoreDbContext))]
    [Migration("20250604180339_ValorAtributo-TipoMovKardexEntrada")]
    partial class ValorAtributoTipoMovKardexEntrada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreAtributo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Atributo__3214EC07AB1F465C");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07D5CFA9CB");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Cupone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsosActuales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UsosMaximos")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cupones__3214EC0789F96FE7");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Cupones__06370DACEA3BF6E0")
                        .IsUnique();

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DetalleP__3214EC071DE766D1");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Direccione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoDireccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Direccio__3214EC074E055094");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.EstadosPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EstadosP__3214EC07B7070AF0");

                    b.ToTable("EstadosPedido");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Kardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("StockActual")
                        .HasColumnType("int");

                    b.Property<int?>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__KARDEX__3214EC07886BCC24");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("KARDEX");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.ListaDeseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ListaDes__3214EC0724A5DC3E");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListaDeseos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.MetodosPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__MetodosP__3214EC07725674D8");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("EstadoPedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Impuesto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TransaccionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Pedidos__3214EC074497B4A2");

                    b.HasIndex("CuponId");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC076A3D152D");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.ProductoAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("AtributoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC0764D268DC");

                    b.HasIndex("AtributoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoAtributos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07CA43B814");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Subcategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id")
                        .HasName("PK__Subcateg__3214EC07A314AFA0");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Subcategorias");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.TipoMovimientoKardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("Entrada")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__TipoMovi__3214EC07F8C6896C");

                    b.ToTable("TipoMovimientoKardex");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07B49ACA59");

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.DetallePedido", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("PedidoId")
                        .HasConstraintName("FK__DetallePe__Pedid__6B24EA82");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Producto", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__DetallePe__Produ__6C190EBB");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Direccione", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Direccion__Usuar__5629CD9C");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Kardex", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Producto", "Producto")
                        .WithMany("Kardices")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__KARDEX__Producto__72C60C4A");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.TipoMovimientoKardex", "TipoMovimiento")
                        .WithMany("Kardices")
                        .HasForeignKey("TipoMovimientoId")
                        .HasConstraintName("FK__KARDEX__TipoMovi__73BA3083");

                    b.Navigation("Producto");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.ListaDeseo", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Producto", "Producto")
                        .WithMany("ListaDeseos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__ListaDese__Produ__5165187F");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Usuario", "Usuario")
                        .WithMany("ListaDeseos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__ListaDese__Usuar__5070F446");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Pedido", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Cupone", "Cupon")
                        .WithMany("Pedidos")
                        .HasForeignKey("CuponId")
                        .HasConstraintName("FK__Pedidos__CuponId__6754599E");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.EstadosPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstadoPedidoId")
                        .HasConstraintName("FK__Pedidos__EstadoP__66603565");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.MetodosPago", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoPagoId")
                        .HasConstraintName("FK__Pedidos__MetodoP__656C112C");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Pedidos__Usuario__6477ECF3");

                    b.Navigation("Cupon");

                    b.Navigation("EstadoPedido");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Producto", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Subcategoria", "Subcategoria")
                        .WithMany("Productos")
                        .HasForeignKey("SubcategoriaId")
                        .HasConstraintName("FK__Productos__Subca__3E52440B");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.ProductoAtributo", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Atributo", "Atributo")
                        .WithMany("ProductoAtributos")
                        .HasForeignKey("AtributoId")
                        .HasConstraintName("FK__ProductoA__Atrib__45F365D3");

                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Producto", "Producto")
                        .WithMany("ProductoAtributos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__ProductoA__Produ__44FF419A");

                    b.Navigation("Atributo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Subcategoria", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Categoria", "Categoria")
                        .WithMany("Subcategoria")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Subcatego__Categ__3A81B327");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Usuario", b =>
                {
                    b.HasOne("Inventario_Productos_Tecnologicos.Models.Role", "RolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Rol")
                        .HasConstraintName("FK__Usuarios__Rol__4CA06362");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Atributo", b =>
                {
                    b.Navigation("ProductoAtributos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Categoria", b =>
                {
                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Cupone", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.EstadosPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.MetodosPago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Producto", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Kardices");

                    b.Navigation("ListaDeseos");

                    b.Navigation("ProductoAtributos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Subcategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.TipoMovimientoKardex", b =>
                {
                    b.Navigation("Kardices");
                });

            modelBuilder.Entity("Inventario_Productos_Tecnologicos.Models.Usuario", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("ListaDeseos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
